name: Build RetroED chico

on:
  push:
    paths:
      - RetroEDv2/**
      - .github/workflows/build.yml
    branches:
      - master

jobs:
  win-build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        cache: true
    - name: Download Jom
      run: |
        Invoke-WebRequest http://download.qt.io/official_releases/jom/jom.zip -OutFile "jom.zip"
        mkdir build
        Expand-Archive -Path jom.zip -DestinationPath build
    - name: Run versiongen
      working-directory: RetroEDv2
      run: |
        py -m pip install pytz
        py versiongen.py $Env:GITHUB_SHA
    - name: Build RetroED
      working-directory: build
      run: |
        qmake ../RetroEDv2/RetroEDv2.pro -spec win32-msvc -config release "CONFIG+=qtquickcompiler" "ENV+=GITHUB_ACTION"
        ./jom -j4
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RetroED-win
        path: build/release/RetroED
  android-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Qt for Android
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        target: 'android'
        arch: 'android_armv7' # O 'android_arm64_v8a' según tu objetivo
        cache: true

    - name: Run versiongen
      working-directory: RetroEDv2
      run: |
        python3 -m pip install pytz
        python3 versiongen.py $GITHUB_SHA

    - name: Build APK
      working-directory: RetroEDv2
      run: |
        mkdir build && cd build
        qmake .. -spec android-clang
        make -j$(nproc)
        make install INSTALL_ROOT=android-build
        androiddeployqt --input android-libRetroEDv2.so-deployment-settings.json --output android-build --gradle

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: RetroED-android
        path: RetroEDv2/build/android-build/build/outputs/apk/
